### ISSUE TITLE
fatal error: nrf_timer.h: No such file or directory

### ISSUE THREAD

**Issue by PeraZver** [khoih-prog/NRF52_TimerInterrupt#2]
Cant compile the code that uses this library. I get the following error message:

    .pio\libdeps\mers\NRF52_TimerInterrupt\src/NRF52TimerInterrupt.h:81:10: fatal error: nrf_timer.h: No such file or directory

I am using:
 * PlatformIO Core, v5.2.4
 * Platform: nordicnrf52 v9.1.0
 * Arduino Core for nRF52, default for Platformio

How can it be? Looking at SDK v17.1.0, nrf_timer.h seems to be an essential file for this lib

**Comment by khoih-prog** [comment]
I compile w/o any issue

![Selection_089](https://user-images.githubusercontent.com/57012152/149687434-db8e6266-5cc3-4eaf-915c-9d8042ce19c6.png)


I suggest you try using Arduino IDE to see if it's OK with your code before going to other demanding platform, such as PIO, etc.

Using those special platforms definitely requires some more knowledge to manually set certain parameters, etc.

If you can't solve yourself, post the issue for help on [PIO Forum](https://community.platformio.org/)

I don't have time to deal with this non-issue.

---

PS:

Posting for help anywhere always requires the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) that you missed. Please be noted any new post will be immediately deleted next time if no MRE is included.

**Comment by PeraZver** [comment]
Thanks for the time to look into it! 
I managed to fix it, it required to switch between two Arduino Cores for nRF52 that PIO supports, Apparently, your lib works only on the  Core made by Adafruit, which I didn't use initially, since I had my own custom board.

**Comment by khoih-prog** [comment]
Thanks for letting us know your experience, which will definitely help other users with the similar problem.

BTW, it's always helpful to first read the [**Prerequisites**](https://github.com/khoih-prog/NRF52_TimerInterrupt#prerequisites) and realize that only [**Adafruit_nRF52_Arduino** core](https://github.com/adafruit/Adafruit_nRF52_Arduino) is currently supported.

You can also use your custom board with Adafruit core by creating certain files in [**variants** directory](https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master/variants), for examples [**NINA_B112_ublox**](https://github.com/khoih-prog/NRF52_TimerInterrupt/tree/main/Packages_Patches/adafruit/hardware/nrf52/1.2.0/variants/NINA_B112_ublox)

Good Luck with your project,
